name: Build Sample Projects

on:
  push:
    branches: main
  pull_request:
    branches: '**'

jobs:
  buildLatestProject:
    name: "Build Latest Project"
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd Sample\ Projects/RxSwift\ 6\ App/
          xcodebuild clean -project RxSwift\ 6\ App.xcodeproj -scheme RxSwift\ 6\ App -destination "generic/platform=iOS"